name: CI

env:
  MARIMO_SKIP_UPDATE_CHECK: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.9

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.8
          cache: pnpm

      - name: 📥 Install dependencies
        run: pnpm install

      - name: 🧹 Lint
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.9

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.8
          cache: pnpm

      - name: 📥 Install dependencies
        run: pnpm install

      - name: ʦ Typecheck
        run: pnpm typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.9

      - name: 🐍 Setup uv
        uses: astral-sh/setup-uv@v6

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.14.0

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.6
          cache: pnpm

      - name: 📥 Install dependencies
        run: |
          uv pip install marimo --system
          pnpm install

      - name: 🧪 Run tests
        run: pnpm test


